//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDBSys.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AllUsers
    {
        public int userId { get; set; }
        public string userFName { get; set; }
        public string userLName { get; set; }
        public string userAddress { get; set; }
        public string userEmail { get; set; }
        public string userPhone { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public Nullable<int> roleId { get; set; }
        public string createdBy { get; set; }
    }
}
